config/routes.rb
Rails.application.routes.draw do
  root 'main#index', as: 'home'
  get 'attempts/index', as: 'attempts'
  get 'variants/index', as: 'variants'
  get 'teachers_disciplines/index', as: 'tdis'
  get 'teachers/index', as: 'teachers'
  get 'students/index', as: 'students'
  get 'disciplines/index', as: 'disciplines'
  get 'questions/index', as: 'questions'
  get "persons/index", as: 'persons'

  get 'students/new', as: 'studnew'
  post 'students/create', to: "students#create"
  post "students/destroy/:id", to: "students#destroy"
  post '/students/update/:id', to: "students#update"
  post '/students/edit/:id', to: "students#edit"

  post '/teachers_disciplines/create', to: "teachers_disciplines#create"
  post '/teachers_disciplines/add', to: "teachers_disciplines#add"
  post '/teachers_disciplines/destroy/:id', to: "teachers_disciplines#destroy"
  post '/teachers_disciplines/update/:id', to: "teachers_disciplines#update"
  post '/teachers_disciplines/edit/:id', to: "teachers_disciplines#edit"

  post '/teachers/create', to: "teachers#create"
  post '/teachers/add', to: "teachers#add"
  post '/teachers/destroy/:id', to: "teachers#destroy"
  post '/teachers/update/:id', to: "teachers#update"
  post '/teachers/edit/:id', to: "teachers#edit"

  post '/persons/update/:id', to: "persons#update"
  post '/persons/edit/:id', to: "persons#edit"

  post '/disciplines/create', to: "disciplines#create"
  post '/disciplines/add', to: "disciplines#add"
  post '/disciplines/destroy/:id', to: "disciplines#destroy"
  post '/disciplines/update/:id', to: "disciplines#update"
  post '/disciplines/edit/:id', to: "disciplines#edit"

  post '/questions/create', to: "questions#create"
  post '/questions/add', to: "questions#add"
  post '/questions/destroy/:id', to: "questions#destroy"
  post '/questions/update/:id', to: "questions#update"
  post '/questions/edit/:id', to: "questions#edit"

  post '/variants/create', to: "variants#create"
  post '/variants/add', to: "variants#add"
  post '/variants/destroy/:id', to: "variants#destroy"



  post '/attempts/create', to: "attempts#create"
  post '/attempts/add_student', to: "attempts#add_student"

  post '/attempts/add_discipline', to: "attempts#add_discipline"
  post '/attempts/add_dis', to: "attempts#add_dis"

  post '/attempts/add_variant', to: "attempts#add_variant"
  post '/attempts/add_var', to: "attempts#add_var"

  post '/attempts/add_teacher', to: "attempts#add_teacher"
  post '/attempts/add_tea', to: "attempts#add_tea"

  post '/attempts/add_other', to: "attempts#add_other"
  post '/attempts/add_oth', to: "attempts#add_oth"

  post '/attempts/destroy/:id', to: "attempts#destroy"
end

app/models/student.rb
class Student < ApplicationRecord
  self.table_name = "students"
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    sql = "select * from students order by id desc limit 50"
    @students = ActiveRecord::Base.connection.exec_query(sql)
  end
  def new
  end

  def create
    @pers = Person.new({first_name: params[:first_name], second_name: params[:second_name], patronymic: params[:patronymic], role_id: 'Студент'})
    return unless @pers.save
    flash[:notice] = 'Успех'
    @pers = Person.last
    @student = Student.new({person_id: @pers.id, quota: params[:quota], date_of_entering: params[:date_of_entering]})
    return unless @student.save
    flash[:notice] = 'Успех'
    redirect_to students_path
  end

  def edit
    @student = Student.find_by(id: params[:id])
  end

  def update
    @student = Student.find_by(id: params[:id])
    @student.update({ quota: params[:quota], date_of_entering: params[:date_of_entering], date_of_otchislenie: params[:date_of_otchislenie] })
    redirect_to '/students'
  end

  def destroy
    @st = Student.find_by(id: params[:id])
    @sec = Person.find_by(id: @st.person_id)
    @st.destroy
    @sec.destroy
    redirect_to '/students'
  end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_create_page.html.erb
<div class='top'>
<% unless @student.valid? %>
  <ul>
    <% @student.errors.each do |error| %>
       <div class='alert alert-info'><li><%= error.full_message %></li></div>
    <% end %>
  </ul>
  <% end %>
 </div>

app/views/students/_form.html.erb
<%= form_with url: "/students/update/#{student.id}", method: :post do |form| %>
  <p><%= form.label :patronymic, "Выберите квоту" %></p>
  <%= form.radio_button :quota, 'Платное' %> Платное
  <%= form.radio_button :quota, 'Бюджет' %> Бюджет
  <p><%= form.label :date_of_entering, "Выберите дату поступления" %></p>
  <p><%= form.date_field :date_of_entering, class: 'form-control', id: 'date_of_entering', value: student.date_of_entering %></p>
  <p><%= form.label :date_of_otchislenie, "Выберите дату отчисления (Если надо)" %></p>
  <p><%= form.date_field :date_of_otchislenie, class: 'form-control', id: 'date_of_otchislenie' %></p>
  <p><%= form.submit("Изменить", id: 'btn') %></p>
<% end %>

app/views/students/create.turbo_stream.erb
<%= turbo_stream.update 'error_response-container', partial: 'create_page' %>

app/views/students/edit.turbo_stream.erb
<%= turbo_stream.update "m-body", partial: 'form', locals: {student: @student}%>

app/views/students/index.html.erb
<li><strong><button type="button" class="btn btn-outline-light me-2 text-bg-dark"><%= link_to "Добавить студента", studnew_path, class: 'nav-link px-2 text-white' %></button></strong></li>
<div class="modal fade" id="staticBackdrop" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable modal-lg">
    <div class="modal-content" id="m-body">
        
      </div>
  </div>
</div>
<table class="table">
  <thead>
    <tr>
      <th scope="col">id</th>
      <th scope="col">Фамилия</th>
      <th scope="col">Имя</th>
      <th scope="col">Отчество</th>
      <th scope="col">Квота</th>
      <th scope="col">Дата поступления</th>
      <th scope="col">Дата отчисления</th>
      <th scope="col">Год выпуска</th>
    </tr>
  </thead>
<% @students.each do |el| %>
<% sql = "select first_name, second_name, patronymic from persons where id = '#{el["person_id"]}'"%>
<% ressql = ActiveRecord::Base.connection.exec_query(sql) %>
<% ressql.each do |elem|%>
  <% @first_name = elem["first_name"]%>
  <% @second_name = elem["second_name"]%>
  <% @patronymic = elem["patronymic"]%>
  <% end %>
  <tbody>
    <tr>
      <th scope="row"><%= el["id"] %></th>
      <td><%= @second_name %></td>
      <td><%= @first_name %></td>
      <td><%= @patronymic %></td>
      <td><%= el["quota"] %></td>
      <td><%= el["date_of_entering"] %></td>
      <td><%= el["date_of_otchislenie"] == nil ? '' : el["date_of_otchislenie"] %></td>
      <td><%= el["year_of_out"] == nil ? '' : el["year_of_out"] %></td>
                <td>
                    <div class="container">
                        <div class="row">
                            <div class='col-auto'>
                                <%= form_with url: "/students/edit/#{el["id"]}", method: :post do |form| %>
                                <button type="submit" class="btn btn-outline-light me-2 text-bg-dark" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
                                Изменить
                                </button>
                                <% end %> 
                            </div>
                            <div class='col-auto'>
                                <%= form_with url: "/students/destroy/#{el["id"]}" do |form| %>
                                    <button type="submit" class="btn-close" aria-label="Закрыть"></button>
                                <% end %>  
                            </div>
                        </div>
                    </div>
                </td>
    </tr>
  </tbody>
<%end%>
</table>

app/views/students/new.html.erb
<h4>Создание человека</h4>
<%= form_with url: '/students/create', method: :post do |form| %>
  <p><%= form.label :first_name, "Введите имя" %></p>
  <p><%= form.text_field :first_name, placeholder: 'Имя', class: 'form-control', id: 'first_name' %></p>
  <p><%= form.label :second_name, "Введите фамилию" %></p>
  <p><%= form.text_field :second_name, placeholder: 'Фамилия', class: 'form-control', id: 'second_name'%></p>
  <p><%= form.label :patronymic, "Введите отчество" %></p>
  <p><%= form.text_field :patronymic, placeholder: 'Отчество', class: 'form-control', id: 'patronymic'%></p>
  <%= form.radio_button :quota, 'Платное' %> Платное
  <%= form.radio_button :quota, 'Бюджет' %> Бюджет
  <p><%= form.label :patronymic, "Выберите дату поступления" %></p>
  <p><%= form.date_field :date_of_entering, class: 'form-control', id: 'date_of_entering'%>
  <p><%= form.submit("Создать", id: 'btn') %></p>
<% end %>

<div id='error_response-container'></div>