config/routes.rb
Rails.application.routes.draw do
  root 'main#index', as: 'home'
  get 'attempts/index', as: 'attempts'
  get 'variants/index', as: 'variants'
  get 'teachers_disciplines/index', as: 'tdis'
  get 'teachers/index', as: 'teachers'
  get 'students/index', as: 'students'
  get 'disciplines/index', as: 'disciplines'
  get 'questions/index', as: 'questions'
  get "persons/index", as: 'persons'

  get 'students/new', as: 'studnew'
  post 'students/create', to: "students#create"
  post "students/destroy/:id", to: "students#destroy"
  post '/students/update/:id', to: "students#update"
  post '/students/edit/:id', to: "students#edit"

  post '/teachers_disciplines/create', to: "teachers_disciplines#create"
  post '/teachers_disciplines/add', to: "teachers_disciplines#add"
  post '/teachers_disciplines/destroy/:id', to: "teachers_disciplines#destroy"
  post '/teachers_disciplines/update/:id', to: "teachers_disciplines#update"
  post '/teachers_disciplines/edit/:id', to: "teachers_disciplines#edit"

  post '/teachers/create', to: "teachers#create"
  post '/teachers/add', to: "teachers#add"
  post '/teachers/destroy/:id', to: "teachers#destroy"
  post '/teachers/update/:id', to: "teachers#update"
  post '/teachers/edit/:id', to: "teachers#edit"

  post '/persons/update/:id', to: "persons#update"
  post '/persons/edit/:id', to: "persons#edit"

  post '/disciplines/create', to: "disciplines#create"
  post '/disciplines/add', to: "disciplines#add"
  post '/disciplines/destroy/:id', to: "disciplines#destroy"
  post '/disciplines/update/:id', to: "disciplines#update"
  post '/disciplines/edit/:id', to: "disciplines#edit"

  post '/questions/create', to: "questions#create"
  post '/questions/add', to: "questions#add"
  post '/questions/destroy/:id', to: "questions#destroy"
  post '/questions/update/:id', to: "questions#update"
  post '/questions/edit/:id', to: "questions#edit"

  post '/variants/create', to: "variants#create"
  post '/variants/add', to: "variants#add"
  post '/variants/destroy/:id', to: "variants#destroy"



  post '/attempts/create', to: "attempts#create"
  post '/attempts/add_student', to: "attempts#add_student"

  post '/attempts/add_discipline', to: "attempts#add_discipline"
  post '/attempts/add_dis', to: "attempts#add_dis"

  post '/attempts/add_variant', to: "attempts#add_variant"
  post '/attempts/add_var', to: "attempts#add_var"

  post '/attempts/add_teacher', to: "attempts#add_teacher"
  post '/attempts/add_tea', to: "attempts#add_tea"

  post '/attempts/add_other', to: "attempts#add_other"
  post '/attempts/add_oth', to: "attempts#add_oth"

  post '/attempts/destroy/:id', to: "attempts#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attempt.rb
class Attempt < ApplicationRecord
end

app/models/discipline.rb
class Discipline < ApplicationRecord
  self.table_name = "disciplines"
end

app/models/person.rb
class Person < ApplicationRecord
  self.table_name = "persons"
end

app/models/question.rb
class Question < ApplicationRecord
  self.table_name = "questions"
end

app/models/student.rb
class Student < ApplicationRecord
  self.table_name = "students"
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  self.table_name = "teachers"
end

app/models/teacher_discipline.rb
class TeacherDiscipline < ApplicationRecord
  self.table_name = "teachers_disciplines"
end

app/models/variant.rb
class Variant < ApplicationRecord
  self.table_name = "variants"
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
  def index
    sql = "select * from persons order by id desc limit 500"
    @persons = ActiveRecord::Base.connection.exec_query(sql)
  end

  def edit
    @person = Person.find_by(id: params[:id])
  end

  def update
    @person = Person.find_by(id: params[:id])
    @person.update({role_id: params[:role_id]})
    redirect_to '/persons'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attempts_helper.rb
module AttemptsHelper
  def all_students
    sql = "select students.id, first_name, second_name, patronymic from persons, students where students.person_id = persons.id and students.date_of_otchislenie is NULL order by students.id desc limit 500"
    res = ActiveRecord::Base.connection.exec_query(sql)
    @fios = []
    res.each do |el|
      fio = "#{el["second_name"]} #{el["first_name"]} #{el["patronymic"]}"
      @fios.push([fio, el["id"]])
    end
    @fios
  end
end

app/helpers/disciplines_helper.rb
module DisciplinesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/variants_helper.rb
module VariantsHelper
end

app/views/header/_header.html.erb
<header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom header">
      <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
        <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"/></svg>
        <span class="fs-4"><strong><span class='purple'>Внутренний экзамен университета</span></strong></span>
      <div class='text-right'>
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-3 mb-md-0">
              <li><strong><button type="button" class="btn btn-outline-light me-2 text-bg-dark"><%= link_to "Главная страница", home_path, class: 'nav-link px-2 text-white' %></button></strong></li>
            <li><strong><button type="button" class="btn btn-outline-light me-2 text-bg-dark"><%= link_to "Преподаватели и дисциплины", tdis_path, class: 'nav-link px-2 text-white' %></button></strong></li>
            <li><strong><button type="button" class="btn btn-outline-light me-2 text-bg-dark"><%= link_to "Студенты", students_path, class: 'nav-link px-2 text-white' %></button></strong></li>
             <li><strong><button type="button" class="btn btn-outline-light me-2 text-bg-dark"><%= link_to "Преподаватели", teachers_path, class: 'nav-link px-2 text-white' %></button></strong></li>
            <li><strong><button type="button" class="btn btn-outline-light me-2 text-bg-dark"><%= link_to "Все люди", persons_path, class: 'nav-link px-2 text-white' %></button></strong></li>
            <li><strong><button type="button" class="btn btn-outline-light me-2 text-bg-dark"><%=link_to "Дисциплины", disciplines_path, class: 'nav-link px-2 text-white' %></button></strong></li>
            <li><strong><button type="button" class="btn btn-outline-light me-2 text-bg-dark"><%= link_to "Вопросы", questions_path, class: 'nav-link px-2 text-white' %></button></strong></li>
            <li><strong><button type="button" class="btn btn-outline-light me-2 text-bg-dark"><%= link_to "Варианты", variants_path, class: 'nav-link px-2 text-white' %></button></strong></li>
            <li><strong><button type="button" class="btn btn-outline-light me-2 text-bg-dark"><%= link_to "Попытки", attempts_path, class: 'nav-link px-2 text-white' %></button></strong></li>
        </ul>
         </div>
      </a>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CourseWork</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-uWxY/CJNBR+1zjPWmfnSnVxwRheevXITnMqoEIeG1LJrdI0GlVs/9cVSyPYXdcSF" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ" crossorigin="anonymous"></script>
  </head>
      <%= render 'header/header' %>
  <body>
  <% flash.each do |type, msg| %>
      <div class='alert alert-info'>
        <strong id='msg'><%= msg %></strong>
      </div> 
    <% end %>
    <%= yield %>
  </body>
</html>